# -*- coding: utf-8 -*-
"""day_25_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAQYNHLZewH8WiVaSIPGH8IVMNXLYcpI
"""

# flask is a web application framework

from flask import Flask, render_template,request  # falsk use connect to server and create a \web page od data

# render tempoalte

import pickle
import numpy as np

# pckle a module to serialize and deserialize python objects

model=pickle.load(open('spamclassifier_MnB (1).pkl','rb'))
vectorizer=pickle.load(open('vectorizer.pkl','rb'))  # change text data  into numerical  use vectorizer

app=Flask(__name__) # creating the flask object

# @app.route('/')
# def home():
#     return "hello ,this ia our first flask website ";

# if __name__=='__main__':
#     app.run(debug=True)

@app.route('/',methods=['POST','GET'])  # redirect to home page
def home():
  return render_template('index.html')

# render tempalte use redirect to another template

@app.route('/predict,method=[POST,GET]')
def predict():
  try:
    if request.method=='POST':
      messg=str(request.form['mesg'])
      transformed=vectorizer.transform([messg])
      transformed_data=transformed.toarray()
      pred=model.predict(transformed_data)
      output =str(pred[0])
      return render_template('result.html',prediction=f"(output)")
  except Exception as e:
    return render_template('result.html',prediction=f"(Error: {str(e)})")

if __name__=='__main__':
  app.run(host="0.0.0.0",port=5000,debug=True) # when we update anything then it update automatically